### ISSUE TITLE
Unable to discover package class

### ISSUE THREAD

**Issue by Ralphkay** [hnhdigital-os/laravel-number-converter#3]
After installing the package and running the ordinal function in the template this is what i get 
**_`Class 'Bluora\PhpNumberConverter\NumberConverter' not found`_**, if i add the **::class** to it in the config/app i get `**_Class 'HnhDigital\LaravelNumberConverter\Facade::class' not found_**`

Any help please?

**Comment by RoccoHoward** [comment]
@Ralphkay Just released a new version with updated namespace. This should fix that first error of not finding Bluora (it's changed to HnhDigital namespace)

**Comment by Ralphkay** [comment]
Will have to check. Thanks a lot !
