### ISSUE TITLE
PHP 8 Support

### ISSUE THREAD

**Issue by mikebronner** [hnhdigital-os/laravel-number-converter#9]
Hi, I just tried installing the package, and got the composer error that it is not yet PHP 8 compatible. Is there anything in the code that would prevent `composer.json` from being updated? I would be happy to submit a PR.

Thanks :)

**Comment by RoccoHoward** [comment]
I don't believe so! Send through a PR and happy to review and approve!

**Comment by aldok10** [comment]
![image](https://user-images.githubusercontent.com/20703405/112784742-9d0ab080-907c-11eb-862a-e776e3d9a59a.png)
i have been error when install on php 8 cz hnhdigital-os/php-number-converter on non dev-master is still just use php 7

**Comment by RoccoHoward** [comment]
Should work fine now. I hadn't tagged a release with the updated composer file.

**Comment by slimani-dev** [comment]
@RoccoHoward please create a minor release for this commit i hade to use :dev-master with composer to get the update

**Comment by RoccoHoward** [comment]
@moh-slimani Done  - let me know if that works?
